### ISSUE TITLE
error launching tclapp/entry.tcl

### ISSUE THREAD

**Issue by ColdfireMC** [ActiveState/tdk#9]
I'm having the following error durinf tclapp init

can't find package as::tdk::obfuscated
    while executing
"package require as::tdk::obfuscated"
    (file "/usr/src/tdk/tdk.git/trunk/lib/wrapengine/wengine.tcl" line 30)
    invoked from within
"source /usr/src/tdk/tdk.git/trunk/lib/wrapengine/wengine.tcl"
    ("package ifneeded tclapp::wrapengine 1.0" script)
    invoked from within
"package require tclapp::wrapengine"
    (file "/usr/src/tdk/tdk.git/trunk/lib/wrapengine/tclapp.tcl" line 35)
    invoked from within
"source /usr/src/tdk/tdk.git/trunk/lib/wrapengine/tclapp.tcl"
    ("package ifneeded tclapp 1.0" script)
    invoked from within
"package require  tclapp"
    (file "/usr/src/tdk/tdk.git/trunk/app/tclapp/lib/app-tclapp/tclapp_startup.tcl" line 56)
    invoked from within
"source /usr/src/tdk/tdk.git/trunk/app/tclapp/lib/app-tclapp/tclapp_startup.tcl"
    ("uplevel" body line 1)
    invoked from within
"uplevel \#0 [list source $file]"
    (procedure "go" line 17)
    invoked from within
"go [file join $starkit::topdir lib app-tclapp tclapp_startup.tcl]"
    (file "entry.tcl" line 56)

**Comment by daper** [comment]
Could you explain what did you do to reproduce it?

**Comment by ColdfireMC** [comment]
Just sourcing app/entry.tcl from tclsh. A debug trace/log would be useful?

**Comment by daper** [comment]
The package you are missing is located under [lib/misc/as-tdk-obfuscated.tm](https://github.com/ActiveState/tdk/blob/master/lib/misc/as-tdk-obfuscated.tm). Ensure you have it on your [tm::path](https://www.tcl.tk/man/tcl/TclCmd/tm.html).

**Comment by mujinjia** [comment]
I would like to ask you how to compile into an executable TDK program?

**Comment by cyangy** [comment]
Hi, @ColdfireMC. I just take a few days to make it works, please refer to [this link](https://github.com/cyangy/tdk/blob/master/Run.md).

**Comment by ColdfireMC** [comment]
Following the tutorial makes it work. Thanks for the advice. It would be useful to have an install makefile or something like that
